### ISSUE TITLE
Blank lines aren't ignored

### ISSUE THREAD

**Issue by ahenshaw** [dandxy89/lp_parser_rs#25]
In this simple LP file
```
\ LP format example

Minimize
obj:  x + 10 y
Subject To
r01:  x + y  >= 1
Binaries
 x y
End

```
if I add a blank line before "Binaries", then the Binaries section is not read.  Looking at the Pest file, it seems that blank lines aren't handled as specified in the [IBM specs](https://www.ibm.com/docs/en/icos/22.1.1?topic=representation-comments-in-lp-file-format).

**Comment by dandxy89** [comment]
Thanks for all the feedback much appreciated. 

I'll take a look at all three in the morning.

**Comment by ahenshaw** [comment]
Thanks! And thanks for developing this library!


I'm using it in my project: https://github.com/ahenshaw/balas
________________________________

**Comment by ahenshaw** [comment]
I don't think this is fixed everywhere.  The specific example that I gave above is fixed, but if I add the blank line after "Binaries", then it doesn't work.  My understanding of the spec is that blank lines should be ignored everywhere.

**Comment by ahenshaw** [comment]
Also, I believe comments should be more universally allowed.  In the example below, I wanted to comment out two constraints, but the parser gives this error:```

Caused by:
     --> 4:1
      |
    4 | \ c001:    - 2 x1 + 6 x2 - 3 x3 + 4 x4 + 1 x5 - 2 x6 >=  2
      | ^---
      |
      = expected CONSTRAINT
```
```
Minimize
    obj: 3x1 + 5x2 + 6x3 + 9x4 + 10x5 + 10x6
Subject To
\ c001:    - 2 x1 + 6 x2 - 3 x3 + 4 x4 + 1 x5 - 2 x6 >=  2
\ c002:    - 5 x1 - 3 x2 + 1 x3 + 3 x4 - 2 x5 + 1 x6 >= -2
c003:      5 x1 - 1 x2 + 4 x3 - 2 x4 + 2 x5 - 1 x6 >=  3
Binaries
    x1 x2 x3 x4 x5 x6
End

```

**Comment by dandxy89** [comment]
Appreciate all the feedback. Let me take another look at this tonight.

**Comment by ahenshaw** [comment]
Blank lines everywhere seem to work properly.  However, still can't put comments everywhere. I believe that is the last issue that I've run across.  Great job on this!

**Comment by dandxy89** [comment]
I'm not going to have any time this evening to look into this.

Will take a look tomorrow at this tomorrow

**Comment by dandxy89** [comment]
@ahenshaw, could you give it another shot? If it doesn't work out, could you share examples of what's not functioning properly?

**Comment by ahenshaw** [comment]
This passes all of the tests that I have.  Great job!
My repo is https://github.com/ahenshaw/balas

**Comment by dandxy89** [comment]
Thanks for sharing - will review it over the weekend and see if there is anything I can do in lp_parser that could assist with the work you're doing over there.
