### ISSUE TITLE
Labels are required

### ISSUE THREAD

**Issue by ahenshaw** [dandxy89/lp_parser_rs#26]
In this simple LP file:
```
\ LP format example

Minimize
obj:  x + 10 y
Subject To
r01:  x + y  >= 1
Binaries
 x y
End
```
If I remove the "obj:" label, then "x" is taken as the name of the objective and not processed as part of the equation.

**Comment by dandxy89** [comment]
@ahenshaw 

All of the issues raised should now be resolved. Would you mind re-testing?

Glad you've found this repo useful.

**Comment by ahenshaw** [comment]
Your fix to allow no labels for constraints works!
