### ISSUE TITLE
Empty Bounds sections should be allowed

### ISSUE THREAD

**Issue by ahenshaw** [dandxy89/lp_parser_rs#27]
With binary-variable problems, Gurobi will insert a Bounds section that only has the line "Bounds".  Like so:
```
\ LP format example

Minimize
obj:  x + 10 y
Subject To
r01:  x + y  >= 1
Bounds
Binaries
 x y
End
```
This seems to cause the parser to miss the "Binaries" line.

**Comment by dandxy89** [comment]
Thanks for raising. I'll fix this in the morning.
